### ISSUE TITLE
how to troubleshoot?

### ISSUE THREAD

**Issue by howardjones** [Super-Visions/cacti-plugin-autom8thold#2]
I'm working on updating one of my Cacti installation to the latest versions, and started with a copy of my current 0.8.7e (!) installation, to test the update procedure.

Upgrade to 0.8.8d worked fine, and I've now also upgraded all the plugins. I wanted to also try autom8thold, since I already use thold and autom8. I've patched autom8, installed autom8thold, and the UI seems to work OK - I can create rules, and the UI behaves as expected.

However, no thresholds are created. I also don't see any mention of AUTOM8 in the logs that isn't for graphs.

How can I troubleshoot this? I originally chose the 'apply autom8 rules' for individual devices in the Hosts page but no thresholds were created (the hosts and DS were listed correctly in the rule-editing page). I already dropped my threshold templates and re-installed that plugin, since the database tables have changed a bit in the last few versions, so that is now a fresh install with only two thold templates. I have also reindexed all hosts, but still no thresholds.

Also, just to confirm - "Apply Thresholds" _does_ create the threshold correctly, so I'm pretty sure that part is OK, too.

(originally here: http://forums.cacti.net/viewtopic.php?f=17&t=54774)

**Comment by Hipska** [comment]
Will take this further in the linked forum topic..
